name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
        
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: jekyllcms
          server: host.fuelwebmarketing.com
          port: 522 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
          
          # will put all file under this path
          local_path: /srv/jekyll/_site/* # default is ./*
          # files will copy to under remote_path
          remote_path: /home/jekyllcms/public_html/
        
          # sftp args
          args: '-o ConnectTimeout=5'
        
